#!/bin/bash                                                                                          
                                                                                                     
# Convert plain text to base64                                                                       
                                                                                                     
echo "                                                                                               
The text '$*' has been converted to base64                                                             
"                                                                                                    
                                                                                                     
echo "$*" | base64                                                                                   
                                                                                                     
echo ""                                                                                             
                                                                                                     
exit 0  
