#!/bin/bash
# -e option is to convert plain text into base64
# -d option is to convert base64 to plain text
# -f option is to convert plain text to base32
# -g option is to convert base32 to plain text
# -h option is to convert Hexadecimal to plain text 
while [ -n "$1" ]
do
case "$1" in
-e)echo ""
read -p "Enter word or phrase you want converted to Base64: " text
echo "
Your text '$text' was converted to base64"
        echo ""
echo "$text" | base64
        echo "" ;;
-d)echo ""
read -p "Enter base64: " base
        echo ""
echo "$base" | base64 -d
        echo "" ;;
-f)echo ""
read -p "Enter word or phrase you want converted to Base32: " text
echo "
Your text '$text' was converted to base32"
        echo ""
echo "$text" | base32
        echo "" ;;
-g)echo ""
read -p "Enter base32: " base
        echo ""
echo "$base" | base32 -d
        echo "" ;;
-h)echo ""
read -p "Enter hex you want converted into text: " hex
        echo ""
echo "$hex" | sed 's/ //g' | perl -pe 's/([0-9a-f]{2})/chr hex $1/gie'
        echo "" ;;
-c)echo ""                                                                                                                                                 
        read -p "Enter plain text to convert to Hexadecimal: " Hex                                                                                         
                echo ""                                                                                                                                    
        echo -n "$Hex" | od -A n -t x1                                                                                                             
                echo "" ;;
--help)echo ""
        echo "The available options are listed below -
# -e option is to convert plain text into base64
# -d option is to convert base64 to plain text
# -f option is to convert plain text to base32
# -g option is to convert base32 to plain text
# -h option is to convert Hexadecimal to plain text
# -c option is to convert plain text to Hexadecimal"
        echo "" ;;        
*)echo ""
echo -e "\033[31mOption \033[34m$1\033[0m \033[31mis not an option, use --help for options\033[0m"
        echo ""
esac
shift
done
exit 0
