#!/bin/bash

read -p "choose a number to use: " number
if [ "$number" = "1" ] ; then
	read -p "Enter word or phrase you want encoded in Base64: " encode64
	    echo "$encode64" | base64
	    echo
elif [ "$number" = "2" ] ; then
	read -p "Enter base64: " decode64
	    echo "$decode64" | base64 -d
	    echo
elif [ "$number" = "3" ] ; then
	read -p "Enter plain text to convert to Hexadecimal: " Hex
	    echo "$Hex" | od -A n -t x1
	    echo
elif [ "$number" = "4" ] ; then
	read -p "Enter Hexadecimal: " dhex
	echo "$dhex" | sed 's/ //g' | perl -pe 's/([0-9a-f]{2})/chr hex $1/gie'
	echo
fi
